name: 'ue-build-github-action'
description: 'Setup Perforce GitHub action'
inputs:
  project-directory:
    description: >
      Open the project at the given path. If the pathname contains spaces, enclose it in quotes.
    required: false
    default: ${{ github.workspace }}
  version:
    description: >
      Specify the UE version to be used.
      If 'project' is specified, the specified version from the target uproject is used.
      ex) UE_4.27, UE_5.10, project
    required: true
    default: project
  install-directory:
    description: >
      If the UE installation location is not the default, specify the path in this parameter.
      The path must exclude the version number.
      ex) E:\Epic Games\
  build-target:
    description: >
      Allows the selection of an active build target before loading a project.
      
      Possible options are:
      Win64, iOS, Android.
    required: true
  configuration:
    description: >
      The configuration to use when building the app.
      Defaults to 'Debug'

      Possible options are:
      Debug, Development, Shipping.
    required: false
    default: 'Debug'
  enable-package:
    description: >
      Do you want to package it?
      If true, BuildCookRun is executed.
    required: false
    default: false
  package-path:
    description: >
      Path to output packaged files.
    required: false
    default: ${{ runner.temp }}\${{ github.run_number }}.zip
  compression:
    description: >
      Compression Level 0-Copy 9-Best Compression
    required: false
    default: 5
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "upload-cloud"
  color: "orange"